### ISSUE TITLE
Advice needed for Python version requirement

### ISSUE THREAD

**Issue by meri-maki** [nejcm/pr-summary-github-action#9]
Hi! I'm so happy to find your action, it's exactly what i was looking for!
However, i'm encountering an issue with running it

```
Run actions/setup-python@v5
  with:
    python-version-file: .python-version
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
  env:
    CI: true
    FRONTEND_VERSION: 15.12
    pythonLocation: /opt/hostedtoolcache/Python/3.13.2/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib
    UV_CACHE_DIR: /home/runner/work/_temp/setup-uv-cache
Error: The specified python version file at: .python-version doesn't exist.
```

I tried setting python before this step and it didn't work

```
- name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  update-environment: true
```

do i need to add .python-version to my repo? or how should it work?
Will be super thankful for the advice!

![Image](https://github.com/user-attachments/assets/3f40f4a2-deba-46b1-afcd-70904095ebeb)
